- hosts: monitored
  tags: prometheus_exporter
  roles:
    - role: prometheus.prometheus.process_exporter
    - role: prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.systemd_exporter
  tasks:
    - name: Open port 9256 for process exporter
      become: true
      ansible.builtin.firewalld:
        port: 9256/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Open port 9100 for node exporter
      become: true
      ansible.builtin.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Open port 9558 for systemd exporter
      become: true
      ansible.builtin.firewalld:
        port: 9558/tcp
        permanent: true
        state: enabled
        immediate: true

- hosts: grafana
  tags: grafana
  become: true
  name: Install Grafana and Configure
  vars:
    prometheus_url: "http://{{ hostvars['node2']['ansible_host'] }}:9090"
    grafana_url: "http://{{ hostvars['node1']['ansible_host'] }}:3000"
    admin_user: admin
    admin_password: test
    allow_sign_up: false
  roles:
    - role: grafana_install

  tasks:
    - name: create prometheus datasource
      community.grafana.grafana_datasource:
        name: prometheus
        ds_type: prometheus
        grafana_url: "{{ grafana_url }}"
        grafana_user: "{{ admin_user }}"
        grafana_password: "{{ admin_password }}"
        ds_url: "{{ prometheus_url }}"
        state: present
    - name: Install/update Grafana piechart panel plugin
      become: true
      community.grafana.grafana_plugin:
        name: marcusolsson-treemap-panel
        version: latest
        state: present
    - name: Restart Grafana
      become: true
      systemd:
        name: grafana-server
        state: restarted

- hosts: prometheus
  tags: prometheus
  roles:
    - role: prometheus.prometheus.prometheus
      tags: prometheus
      vars:
        no_log: false
        prometheus_storage_retention: 365d
        prometheus_global:
          scrape_interval: 10s
          evaluation_interval: 5s
          scrape_timeout: 10s
        prometheus_scrape_configs:
          - job_name: node_exporter
            scrape_interval: 5s
            static_configs:
              - targets: "{{ groups['monitored'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:9100') | list }}"
          - job_name: process_exporter
            scrape_interval: 5s
            static_configs:
              - targets: "{{ groups['monitored'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:9256') | list }}"
          - job_name: systemd_exporter
            scrape_interval: 5s
            static_configs:
              - targets: "{{ groups['monitored'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:9558') | list }}"
          - job_name: pve_exporter
            scrape_interval: 5s
            metrics_path: "/pve"
            static_configs:
              - targets: "{{ groups['proxmox'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:9221') | list }}"
            params:
              module: [default]
            # relabel_configs:
            #   - source_labels: [__address__]
            #     target_label: __param_target
            #   - source_labels: [__param_target]
            #     target_label: instance
            #   - target_label: __address__
            #     replacement: "192.168.0.11:9221"
  tasks:
    - name: Open port 9090 for prometheus
      become: true
      ansible.builtin.firewalld:
        port: 9090/tcp
        permanent: true
        state: enabled
        immediate: true
