# Create new user for ansible
- name: Boostrap Ansible
  tasks:
    - name: Create new user for ansible
      ansible.builtin.user: # could be done in on the copy of the ssh key
        name: "ansible"
        shell: /bin/bash
        group: ansible
        create_home: true
        comment: ansible user

    - name: Know if the sudoers file exists
      ansible.builtin.stat:
        path: /etc/sudoers.d/ansible
      register: sudoers_file_exists

    - name: Add sudoers file
      ansible.builtin.file:
        path: /etc/sudoers.d/ansible
        state: touch
        mode: "0440"
        owner: root
        group: root
      changed_when: sudoers_file_exists.stat.exists is defined and sudoers_file_exists.stat.exists == false

    - name: Edit sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        state: present
