@startuml "Component"


package VsRecorder{
  [Extension VsCode] -> "Json"
}



package VsLoader{
  "Json" -left-> [Runner]
  [Browser]
  [Runner]
  Runner -> Browser : Manipulate
}


component Server{
  [CLI] --> [Code Binary] : Install
  portin 22
  portout 8080
}

22 -> CLI

Runner --> 22: ssh
Browser --> 8080: Code web
8080 --> [Code Binary]

note left of 8080
  Openned port by CLI
end note

note as JsonNote
  Json student behavior
end note

JsonNote .. Json

@enduml
