@startuml "Solution"

package Proxmox{
  [Proxmox exporter] as exporterPVE
  component CENTos{
    [Node exporter] as exporter
  }
}

database Prometheus{

}

package Grafana{
  [Dashboard Proxmox]
  [Dashboard Proxmox Node]
}

Grafana ---> Prometheus : Query
exporterPVE --> Prometheus : Metrics
exporter -> Prometheus : Metrics

@enduml
