@startuml "Sequence vsloader"

participant "VsBuilder" as builder
participant "VsLoader" as vsloader
participant "Browser" as browser
participant "Server" as vm


builder -> vsloader: config.json
vsloader -> vm: ssh connection
vm -> vsloader: connection established
vsloader -> vm: Install vscoder server
vm -> vsloader: vscoder server installed
vsloader -> vm: Open port set in config
vm -> vsloader: port opened
vsloader -> browser: Open browser
browser -> vsloader: connect to vscoder server
loop until student simulation ends
    vsloader -> browser: Interact with code
    vm -> browser: code changes reflected
end
browser -> vsloader: close browser
vsloader -> vm: close port
vm -> vsloader: port closed
vsloader -> vm: uninstall vscoder server
vm -> vsloader: vscoder server uninstalled
vsloader -> vm: close ssh connection
vm -> vsloader: ssh connection closed
vsloader -> builder: simulation ends
@enduml
